#!/bin/bash
# Runs mruby's own benchmarks (benchmark/bm_*.rb of the reference tree) on the reference
# `mruby` (Docker) and on SabiRuby, and writes docs/bench.md.
#   tools/bench.sh            # all benchmarks, 3 runs each, best time
#   tools/bench.sh fib        # one benchmark (substring match)
# Reference times are measured inside the container (date +%s%N around `mruby`), SabiRuby
# times on the host (release build, `sabiruby run --stats`). Same machine, same .mrb.
set -eu
cd "$(dirname "$0")/.."
IMG=kishima/mruby:4.1.0-rc
MRUBY=${MRUBY_SRC:-../../ref/mruby}
DIR=bench
RUNS=${RUNS:-3}
mkdir -p $DIR/src
cp "$MRUBY"/benchmark/bm_*.rb "$MRUBY"/benchmark/vm_optimization_bench.rb $DIR/src/ 2>/dev/null || true
docker run --rm -v "$PWD/$DIR:/w" $IMG /bin/sh -c 'cd /w && for rb in src/*.rb; do b=$(basename $rb .rb); mrbc -o $b.mrb $rb || echo "compile failed: $b"; done'
cargo build --release -q -p sabiruby-cli
best() { sort -n | head -1; }
{
  echo "# Benchmarks: SabiRuby vs mruby 4.1.0-rc"
  echo
  echo "mruby's \`benchmark/*.rb\`, compiled by the reference \`mrbc\`. Best of $RUNS runs. Reference \`mruby\` runs inside the"
  echo "Docker image on the same machine (so the numbers are a ratio, not an absolute). Generated by \`tools/bench.sh\` on $(date -u +%Y-%m-%d)."
  echo
  echo "| benchmark | mruby ms | SabiRuby ms | ratio | instructions | ns/instruction |"
  echo "|---|---:|---:|---:|---:|---:|"
  for mrb in $DIR/*.mrb; do
    b=$(basename $mrb .mrb)
    [ -n "${1:-}" ] && [[ "$b" != *"$1"* ]] && continue
    ref=$(for i in $(seq $RUNS); do docker run --rm -v "$PWD/$DIR:/w:ro" $IMG /bin/sh -c "s=\$(date +%s%N); timeout 300 mruby /w/$b.mrb > /dev/null 2>&1; e=\$(date +%s%N); echo \$(( (e - s) / 1000000 ))"; done | best)
    ours=""; insn=""; nsi=""
    for i in $(seq $RUNS); do
      st=$( { timeout 300 ./target/release/sabiruby run --stats $mrb > /dev/null; } 2>&1 | tail -1 )
      if [[ "$st" == instructions:* ]]; then
        ms=$(echo "$st" | awk '{print $4}'); ins=$(echo "$st" | awk '{print $2}'); n=$(echo "$st" | awk '{print $6}')
        if [ -z "$ours" ] || (( $(echo "$ms < $ours" | bc -l) )); then ours=$ms; insn=$ins; nsi=$n; fi
      else
        ours="fail: $(echo "$st" | cut -c1-60)"; break
      fi
    done
    if [[ "$ours" == fail* ]]; then
      echo "| $b | $ref | $ours | | | |"
    else
      ratio=$(echo "scale=2; $ours / $ref" | bc -l)
      echo "| $b | $ref | $ours | ${ratio}x | $insn | $nsi |"
    fi
  done
} > docs/bench.md
cat docs/bench.md
