#!/bin/bash
# Runs mruby's own test suite (test/assert.rb + test/t/*.rb of the reference tree)
# on SabiRuby and writes docs/mrbtest.md (per-file table + opcode coverage).
#   tools/mrbtest.sh            # compile (Docker, reference mrbc) + run + write docs/mrbtest.md
#   tools/mrbtest.sh --update   # also refresh tests/mrbtest/baseline.txt (the regression floor)
#   tools/mrbtest.sh -v hash    # print the full output of one file
set -eu
cd "$(dirname "$0")/.."
IMG=kishima/mruby:4.1.0-rc
MRUBY=${MRUBY_SRC:-../../ref/mruby}
DIR=tests/mrbtest
mkdir -p $DIR/src
if [ "${1:-}" = "-v" ]; then
  cargo run --release -q -p sabiruby-cli -- mrbtest -v $DIR/assert.mrb $DIR/${2}.mrb
  exit 0
fi
# copy sources (they are MIT, from mruby test/) and compile.
# Gem tests (mrbgems/<gem>/test/*.rb) are copied as gem_<file>.rb; the gem's
# mrblib is compiled into src/mrblib_<gem>.mrb and loaded by Vm::with_mrblib.
GEMS="mruby-sprintf mruby-metaprog mruby-proc-ext mruby-method mruby-fiber mruby-enumerator mruby-array-ext mruby-enum-ext mruby-hash-ext mruby-range-ext mruby-string-ext mruby-compar-ext mruby-toplevel-ext mruby-enum-chain mruby-enum-lazy mruby-object-ext mruby-symbol-ext mruby-kernel-ext mruby-class-ext mruby-numeric-ext mruby-catch mruby-objectspace mruby-math mruby-random mruby-struct mruby-data mruby-set mruby-time"
# the gem test files are copied afresh (the collision rule below looks at what this run copied)
rm -f $DIR/src/gem_*.rb $DIR/gem_*.mrb
cp "$MRUBY/test/assert.rb" $DIR/src/
cp "$MRUBY"/test/t/*.rb $DIR/src/
mkdir -p target/mrblib
for g in $GEMS; do
  short=${g#mruby-}
  # a test file named like an earlier gem's (numeric.rb of string-ext and numeric-ext)
  # is qualified with its gem: gem_<gem>_<file>.rb
  for rb in "$MRUBY"/mrbgems/$g/test/*.rb; do
    dst=$DIR/src/gem_$(basename "$rb")
    [ -e "$dst" ] && dst=$DIR/src/gem_${short//-/_}_$(basename "$rb")
    cp "$rb" "$dst"
  done
  if ls "$MRUBY"/mrbgems/$g/mrblib/*.rb >/dev/null 2>&1; then
    cat "$MRUBY"/mrbgems/$g/mrblib/*.rb > target/mrblib/mrblib_$short.rb
    docker run --rm -v "$PWD/target/mrblib:/w" $IMG mrbc -o /w/mrblib_$short.mrb /w/mrblib_$short.rb
    cp target/mrblib/mrblib_$short.mrb src/mrblib_$short.mrb
  fi
done
# -g keeps the LVAR section (local variable names): the reference test driver
# compiles the tests from source, so `local_variables` and `Proc#parameters`
# see the names there too.
docker run --rm -v "$PWD/$DIR:/w" $IMG /bin/sh -c '
  mrbc -g -o /w/assert.mrb /w/src/assert.rb
  for rb in /w/src/*.rb; do b=$(basename "$rb" .rb); [ "$b" = assert ] && continue
    mrbc -g -o /w/$b.mrb "$rb" || echo "compile failed: $b"; done'
cargo build --release -q -p sabiruby-cli
{
  echo "# mruby test suite on SabiRuby"
  echo
  echo "Reference: mruby 4.1.0-rc \`test/assert.rb\` + \`test/t/*.rb\`, compiled by the reference \`mrbc\`."
  echo "Generated by \`tools/mrbtest.sh\` on $(date -u +%Y-%m-%d). Do not edit."
  echo
  ./target/release/sabiruby mrbtest $DIR/assert.mrb $(ls $DIR/*.mrb | grep -v assert.mrb) \
    | awk -F'\t' 'NR==FNR { note[$1]=$2; next }
                  /^\| [a-z_0-9]+ \|/ { n=$0; sub(/^\| /, "", n); sub(/ \|.*/, "", n); if (n in note) sub(/\|  \|$/, "| " note[n] " |") }
                  { print }' $DIR/notes.tsv -
  echo
  echo "Why an assertion does not pass, per file: [\`mrbtest-notes.md\`](mrbtest-notes.md) (hand-written; the \`note\` column comes from \`tests/mrbtest/notes.tsv\`)."
} > docs/mrbtest.md
cat docs/mrbtest.md
if [ "${1:-}" = "--update" ]; then
  grep '^| [a-z_0-9]* |' docs/mrbtest.md | grep -v '^| file |' | awk -F'|' '{gsub(/ /,"",$2); gsub(/ /,"",$4); print $2, $4}' > $DIR/baseline.txt
  echo "baseline updated: $DIR/baseline.txt"
fi
