#!/bin/bash
# Runs mruby's own test suite (test/assert.rb + test/t/*.rb of the reference tree)
# on SabiRuby and writes docs/mrbtest.md (per-file table + opcode coverage).
#   tools/mrbtest.sh            # compile (Docker, reference mrbc) + run + write docs/mrbtest.md
#   tools/mrbtest.sh --update   # also refresh tests/mrbtest/baseline.txt (the regression floor)
#   tools/mrbtest.sh -v hash    # print the full output of one file
set -eu
cd "$(dirname "$0")/.."
IMG=kishima/mruby:4.1.0-rc
MRUBY=${MRUBY_SRC:-../../ref/mruby}
DIR=tests/mrbtest
mkdir -p $DIR/src
if [ "${1:-}" = "-v" ]; then
  cargo run --release -q -- mrbtest -v $DIR/assert.mrb $DIR/${2}.mrb
  exit 0
fi
# copy sources (they are MIT, from mruby test/) and compile.
# Gem tests (mrbgems/<gem>/test/*.rb) are copied as gem_<file>.rb; the gem's
# mrblib is compiled into src/mrblib_<gem>.mrb and loaded by Vm::with_mrblib.
GEMS="mruby-fiber mruby-enumerator"
cp "$MRUBY/test/assert.rb" $DIR/src/
cp "$MRUBY"/test/t/*.rb $DIR/src/
mkdir -p target/mrblib
for g in $GEMS; do
  for rb in "$MRUBY"/mrbgems/$g/test/*.rb; do cp "$rb" $DIR/src/gem_$(basename "$rb"); done
  short=${g#mruby-}
  if ls "$MRUBY"/mrbgems/$g/mrblib/*.rb >/dev/null 2>&1; then
    cat "$MRUBY"/mrbgems/$g/mrblib/*.rb > target/mrblib/mrblib_$short.rb
    docker run --rm -v "$PWD/target/mrblib:/w" $IMG mrbc -o /w/mrblib_$short.mrb /w/mrblib_$short.rb
    cp target/mrblib/mrblib_$short.mrb src/mrblib_$short.mrb
  fi
done
docker run --rm -v "$PWD/$DIR:/w" $IMG /bin/sh -c '
  mrbc -o /w/assert.mrb /w/src/assert.rb
  for rb in /w/src/*.rb; do b=$(basename "$rb" .rb); [ "$b" = assert ] && continue
    mrbc -o /w/$b.mrb "$rb" || echo "compile failed: $b"; done'
cargo build --release -q
{
  echo "# mruby test suite on SabiRuby"
  echo
  echo "Reference: mruby 4.1.0-rc \`test/assert.rb\` + \`test/t/*.rb\`, compiled by the reference \`mrbc\`."
  echo "Generated by \`tools/mrbtest.sh\` on $(date -u +%Y-%m-%d). Do not edit."
  echo
  ./target/release/sabiruby mrbtest $DIR/assert.mrb $(ls $DIR/*.mrb | grep -v assert.mrb)
} > docs/mrbtest.md
cat docs/mrbtest.md
if [ "${1:-}" = "--update" ]; then
  grep '^| [a-z_0-9]* |' docs/mrbtest.md | grep -v '^| file |' | awk -F'|' '{gsub(/ /,"",$2); gsub(/ /,"",$4); print $2, $4}' > $DIR/baseline.txt
  echo "baseline updated: $DIR/baseline.txt"
fi
